version: '3.8'

services:
  tcg-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=tcgdb
    volumes:
      - ./postgresql:/var/lib/postgresql